version: '3'
services:
        mysql-master:
                image: "hc/mysql-master:5.7"
                container_name: hc-mysql-master
                restart: always
                ports:
                - "3307:3306"
                environment:
                  MYSQL_ROOT_PASSWORD: 1234567
                  MYSQL_REPLICATION_USER: "root"
                  MYSQL_REPLICATION_PASSWORD: 1234567
                  MAX_CONNECTIONS: 2048
                  MAX_CONNECT_ERRORS: 1024
                  WAIT_TIMEOUT: 180
                  INTERACTIVE_TIMEOUT: 180
                  SERVER_ID: 1
        mysql-slave:
                image: "hc/mysql-slave:5.7"
                container_name: hc-mysql-slave
                restart: always
                ports:
                - "3308:3306"
                environment:
                  MYSQL_ROOT_PASSWORD: 1234567
                  MYSQL_MASTER_SERVICE_HOST: "192.168.209.177"
                  MYSQL_MASTER_SERVICE_POST: 3307
                  MYSQL_REPLICATION_USER: "root"
                  MYSQL_REPLICATION_PASSWORD: 1234567
                  MAX_CONNECTIONS: 2048
                  MAX_CONNECT_ERRORS: 1024
                  WAIT_TIMEOUT: 180
                  INTERACTIVE_TIMEOUT: 180
                  SERVER_ID: 2
                depends_on:
                - mysql-master
                links:
                - mysql-master

        atlas:
                image: "hc/atlas:2.2"
                container_name: hc-atlas
                restart: always
                ports:
                - "1234:1234"
                - "2345:2345"
                environment:
                  ATLAS_USER: root
                  ATLAS_PASS: 1234567
                  MASTER_CONFIG: 192.168.209.177:3307
                  SLAVE_CONFIG: 192.168.209.177:3308,192.168.209.177:3309
                volumes:
                - e:/docker/shellscript/docker-mysql/360Atlas/conf/:/usr/local/mysql-proxy/conf/
                depends_on:
                - mysql-master
                - mysql-slave
